// @generated from the pinned ruwuma rev's endpoint `metadata!` blocks (the contract
// Continuwuity ran under before the slipstream migration). Placeholders are `{}`.
// Regenerate rather than editing by hand; `tests::spec_cross_check` compares it with matrix-spec.
use super::AuthScheme;

pub(super) const AUTH_TABLE: &[(&str, &str, AuthScheme)] = &[
	("GET", "/.well-known/matrix/client", AuthScheme::None),
	("GET", "/.well-known/matrix/server", AuthScheme::None),
	("GET", "/.well-known/matrix/support", AuthScheme::None),
	("GET", "/_continuwuity/admin/rooms/list", AuthScheme::AccessToken),
	("PUT", "/_continuwuity/admin/rooms/{}/ban", AuthScheme::AccessToken),
	("POST", "/_matrix/app/unstable/fi.mau.msc2659/ping", AuthScheme::AccessToken),
	("POST", "/_matrix/app/v1/ping", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/rooms/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/thirdparty/location", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/thirdparty/location/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/thirdparty/protocol/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/thirdparty/user", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/thirdparty/user/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/app/v1/transactions/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/app/v1/users/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/account/3pid", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/account/3pid/add", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/account/3pid/bind", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/account/3pid/delete", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/account/3pid/email/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/r0/account/3pid/msisdn/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/r0/account/3pid/unbind", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/account/deactivate", AuthScheme::AccessTokenOptional),
	("POST", "/_matrix/client/r0/account/password", AuthScheme::AccessTokenOptional),
	("POST", "/_matrix/client/r0/account/password/email/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/r0/account/password/msisdn/requestToken", AuthScheme::None),
	("GET", "/_matrix/client/r0/account/whoami", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/admin/whois/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/auth/{}/fallback/web", AuthScheme::None),
	("GET", "/_matrix/client/r0/capabilities", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/createRoom", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/delete_devices", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/devices", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/devices/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/devices/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/devices/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/directory/list/appservice/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/directory/list/room/{}", AuthScheme::None),
	("PUT", "/_matrix/client/r0/directory/list/room/{}", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/directory/room/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/directory/room/{}", AuthScheme::None),
	("PUT", "/_matrix/client/r0/directory/room/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/join/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/joined_rooms", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/keys/changes", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/keys/claim", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/keys/device_signing/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/keys/query", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/keys/signatures/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/keys/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/knock/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/login", AuthScheme::None),
	("POST", "/_matrix/client/r0/login", AuthScheme::AppserviceToken),
	("GET", "/_matrix/client/r0/login/sso/redirect", AuthScheme::None),
	("POST", "/_matrix/client/r0/logout", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/logout/all", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/notifications", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/presence/{}/status", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/presence/{}/status", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/profile/{}", AuthScheme::None),
	("GET", "/_matrix/client/r0/profile/{}/avatar_url", AuthScheme::None),
	("PUT", "/_matrix/client/r0/profile/{}/avatar_url", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/profile/{}/displayname", AuthScheme::None),
	("PUT", "/_matrix/client/r0/profile/{}/displayname", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/publicRooms", AuthScheme::None),
	("POST", "/_matrix/client/r0/publicRooms", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushers", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/pushers/set", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushrules/", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushrules/global/", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushrules/global/{}/{}/actions", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/pushrules/global/{}/{}/actions", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/pushrules/global/{}/{}/enabled", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/pushrules/global/{}/{}/enabled", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/register", AuthScheme::AppserviceToken),
	("GET", "/_matrix/client/r0/register/available", AuthScheme::None),
	("POST", "/_matrix/client/r0/register/email/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/r0/register/msisdn/requestToken", AuthScheme::None),
	("DELETE", "/_matrix/client/r0/room_keys/keys", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/room_keys/keys", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/room_keys/keys", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/room_keys/keys/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/room_keys/keys/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/room_keys/keys/{}", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/room_keys/version", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/room_keys/version", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/room_keys/version/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/aliases", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/ban", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/context/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/event/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/forget", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/initialSync", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/invite", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/join", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/joined_members", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/kick", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/leave", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/members", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/messages", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/read_markers", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/receipt/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/rooms/{}/redact/{}/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/report/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/rooms/{}/send/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/state", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/rooms/{}/state/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/rooms/{}/state/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/rooms/{}/typing/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/unban", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/rooms/{}/upgrade", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/search", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/sendToDevice/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/sync", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/location", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/location/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/protocol/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/protocols", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/user", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/thirdparty/user/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/user/{}/account_data/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/user/{}/account_data/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/user/{}/filter", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/user/{}/filter/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/user/{}/openid/request_token", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/user/{}/rooms/{}/account_data/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/user/{}/rooms/{}/account_data/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/user/{}/rooms/{}/tags", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/r0/user/{}/rooms/{}/tags/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/r0/user/{}/rooms/{}/tags/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/r0/user_directory/search", AuthScheme::AccessToken),
	("GET", "/_matrix/client/r0/voip/turnServer", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/event_relationships", AuthScheme::AccessToken),
	(
		"POST",
		"/_matrix/client/unstable/fi.mau.msc2659/appservice/{}/ping",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/im.nheko.summary/summary/{}",
		AuthScheme::AccessTokenOptional,
	),
	("GET", "/_matrix/client/unstable/keys/changes", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/keys/claim", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/keys/device_signing/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/keys/query", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/keys/signatures/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/keys/upload", AuthScheme::AccessToken),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc2432/rooms/{}/aliases",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc2858/login/sso/redirect/{}",
		AuthScheme::None,
	),
	("POST", "/_matrix/client/unstable/org.matrix.msc2918/refresh", AuthScheme::None),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc2946/rooms/{}/hierarchy",
		AuthScheme::AccessToken,
	),
	("GET", "/_matrix/client/unstable/org.matrix.msc2965/auth_issuer", AuthScheme::None),
	("GET", "/_matrix/client/unstable/org.matrix.msc2965/auth_metadata", AuthScheme::None),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3030/rooms/{}/timestamp_to_event",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3231/register/org.matrix.msc3231.login.registration_token/validity",
		AuthScheme::None,
	),
	("POST", "/_matrix/client/unstable/org.matrix.msc3575/sync", AuthScheme::AccessToken),
	(
		"DELETE",
		"/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device",
		AuthScheme::AccessToken,
	),
	(
		"PUT",
		"/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device",
		AuthScheme::AccessToken,
	),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device/{}/events",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3856/rooms/{}/threads",
		AuthScheme::AccessToken,
	),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.msc3882/login/get_token",
		AuthScheme::AccessToken,
	),
	("GET", "/_matrix/client/unstable/org.matrix.msc3916/media/config", AuthScheme::AccessToken),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3916/media/download/{}/{}",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3916/media/download/{}/{}/{}",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3916/media/preview_url",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc3916/media/thumbnail/{}/{}",
		AuthScheme::AccessToken,
	),
	("POST", "/_matrix/client/unstable/org.matrix.msc3983/keys/claim", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/org.matrix.msc4108/rendezvous", AuthScheme::None),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc4140/delayed_events",
		AuthScheme::AccessToken,
	),
	(
		"GET",
		"/_matrix/client/unstable/org.matrix.msc4140/delayed_events/{}",
		AuthScheme::AccessToken,
	),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.msc4140/delayed_events/{}",
		AuthScheme::AccessToken,
	),
	("GET", "/_matrix/client/unstable/org.matrix.msc4143/rtc/transports", AuthScheme::None),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.msc4151/rooms/{}/report",
		AuthScheme::AccessToken,
	),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.msc4260/users/{}/report",
		AuthScheme::AccessToken,
	),
	(
		"POST",
		"/_matrix/client/unstable/org.matrix.simplified_msc3575/sync",
		AuthScheme::AccessToken,
	),
	("DELETE", "/_matrix/client/unstable/room_keys/keys", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/room_keys/keys", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/unstable/room_keys/keys", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/unstable/room_keys/keys/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/room_keys/keys/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/unstable/room_keys/keys/{}", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/unstable/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/unstable/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/room_keys/version", AuthScheme::AccessToken),
	("POST", "/_matrix/client/unstable/room_keys/version", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/unstable/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/room_keys/version/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/unstable/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/rooms/{}/relations/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/rooms/{}/relations/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/unstable/rooms/{}/relations/{}/{}/{}", AuthScheme::AccessToken),
	(
		"GET",
		"/_matrix/client/unstable/uk.half-shot.msc2666/user/mutual_rooms",
		AuthScheme::AccessToken,
	),
	("GET", "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}", AuthScheme::None),
	(
		"DELETE",
		"/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}/us.cloke.msc4175.tz",
		AuthScheme::AccessToken,
	),
	(
		"PUT",
		"/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}/us.cloke.msc4175.tz",
		AuthScheme::AccessToken,
	),
	(
		"DELETE",
		"/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}/{}",
		AuthScheme::AccessToken,
	),
	("GET", "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}/{}", AuthScheme::None),
	("PUT", "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{}/{}", AuthScheme::AccessToken),
	(
		"GET",
		"/_matrix/client/unstable/uk.timedout.msc4323/admin/suspend/{}",
		AuthScheme::AccessToken,
	),
	(
		"PUT",
		"/_matrix/client/unstable/uk.timedout.msc4323/admin/suspend/{}",
		AuthScheme::AccessToken,
	),
	("POST", "/_matrix/client/unstable/xyz.amorgan.knock/knock/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v1/appservice/{}/ping", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/auth_metadata", AuthScheme::None),
	("POST", "/_matrix/client/v1/login/get_token", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/media/config", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/media/download/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/media/download/{}/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/media/preview_url", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/media/thumbnail/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/register/m.login.registration_token/validity", AuthScheme::None),
	("GET", "/_matrix/client/v1/room_summary/{}", AuthScheme::AccessTokenOptional),
	("GET", "/_matrix/client/v1/rooms/{}/hierarchy", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/rooms/{}/relations/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/rooms/{}/relations/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/rooms/{}/relations/{}/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/rooms/{}/threads", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v1/rooms/{}/timestamp_to_event", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/account/3pid", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/account/3pid/add", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/account/3pid/bind", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/account/3pid/delete", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/account/3pid/email/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/v3/account/3pid/msisdn/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/v3/account/3pid/unbind", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/account/deactivate", AuthScheme::AccessTokenOptional),
	("POST", "/_matrix/client/v3/account/password", AuthScheme::AccessTokenOptional),
	("POST", "/_matrix/client/v3/account/password/email/requestToken", AuthScheme::None),
	("POST", "/_matrix/client/v3/account/password/msisdn/requestToken", AuthScheme::None),
	("GET", "/_matrix/client/v3/account/whoami", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/admin/whois/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/auth/{}/fallback/web", AuthScheme::None),
	("GET", "/_matrix/client/v3/capabilities", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/createRoom", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/delete_devices", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/devices", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/devices/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/devices/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/devices/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/directory/list/appservice/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/directory/list/room/{}", AuthScheme::None),
	("PUT", "/_matrix/client/v3/directory/list/room/{}", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/directory/room/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/directory/room/{}", AuthScheme::None),
	("PUT", "/_matrix/client/v3/directory/room/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/join/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/joined_rooms", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/keys/changes", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/keys/claim", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/keys/device_signing/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/keys/query", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/keys/signatures/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/keys/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/knock/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/login", AuthScheme::None),
	("POST", "/_matrix/client/v3/login", AuthScheme::AppserviceToken),
	("GET", "/_matrix/client/v3/login/sso/redirect", AuthScheme::None),
	("GET", "/_matrix/client/v3/login/sso/redirect/{}", AuthScheme::None),
	("POST", "/_matrix/client/v3/logout", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/logout/all", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/notifications", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/presence/{}/status", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/presence/{}/status", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/profile/{}", AuthScheme::None),
	("GET", "/_matrix/client/v3/profile/{}/avatar_url", AuthScheme::None),
	("PUT", "/_matrix/client/v3/profile/{}/avatar_url", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/profile/{}/displayname", AuthScheme::None),
	("PUT", "/_matrix/client/v3/profile/{}/displayname", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/profile/{}/m.tz", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/profile/{}/m.tz", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/profile/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/profile/{}/{}", AuthScheme::None),
	("PUT", "/_matrix/client/v3/profile/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/publicRooms", AuthScheme::None),
	("POST", "/_matrix/client/v3/publicRooms", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushers", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/pushers/set", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushrules/", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushrules/global/", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/pushrules/global/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushrules/global/{}/{}/actions", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/pushrules/global/{}/{}/actions", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/pushrules/global/{}/{}/enabled", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/pushrules/global/{}/{}/enabled", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/refresh", AuthScheme::None),
	("POST", "/_matrix/client/v3/register", AuthScheme::None),
	("GET", "/_matrix/client/v3/register/available", AuthScheme::None),
	("POST", "/_matrix/client/v3/register/email/requestToken", AuthScheme::None),
	("GET", "/_matrix/client/v3/register/m.login.registration_token/validity", AuthScheme::None),
	("POST", "/_matrix/client/v3/register/msisdn/requestToken", AuthScheme::None),
	("DELETE", "/_matrix/client/v3/room_keys/keys", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/room_keys/keys", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/room_keys/keys", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/room_keys/keys/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/room_keys/keys/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/room_keys/keys/{}", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/room_keys/keys/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/room_keys/version", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/room_keys/version", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/room_keys/version/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/room_keys/version/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/aliases", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/ban", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/context/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/event/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/forget", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/initialSync", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/invite", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/join", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/joined_members", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/kick", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/leave", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/members", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/messages", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/read_markers", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/receipt/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/rooms/{}/redact/{}/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/report", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/report/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/rooms/{}/send/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/state", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/rooms/{}/state/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/rooms/{}/state/{}/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/rooms/{}/typing/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/unban", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/rooms/{}/upgrade", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/search", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/sendToDevice/{}/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/sync", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/location", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/location/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/protocol/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/protocols", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/user", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/thirdparty/user/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/user/{}/account_data/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/user/{}/account_data/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/user/{}/filter", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/user/{}/filter/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/user/{}/openid/request_token", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/user/{}/rooms/{}/account_data/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/user/{}/rooms/{}/account_data/{}", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/user/{}/rooms/{}/tags", AuthScheme::AccessToken),
	("DELETE", "/_matrix/client/v3/user/{}/rooms/{}/tags/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/client/v3/user/{}/rooms/{}/tags/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/user_directory/search", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v3/users/{}/report", AuthScheme::AccessToken),
	("GET", "/_matrix/client/v3/voip/turnServer", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v4/sync", AuthScheme::AccessToken),
	("POST", "/_matrix/client/v5/sync", AuthScheme::AccessToken),
	("GET", "/_matrix/client/versions", AuthScheme::AccessTokenOptional),
	("POST", "/_matrix/federation/unstable/event_relationships", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/unstable/io.fsky.vel/edutypes", AuthScheme::None),
	(
		"GET",
		"/_matrix/federation/unstable/org.matrix.msc2946/hierarchy/{}",
		AuthScheme::ServerSignatures,
	),
	(
		"GET",
		"/_matrix/federation/unstable/org.matrix.msc3030/timestamp_to_event/{}",
		AuthScheme::ServerSignatures,
	),
	("GET", "/_matrix/federation/unstable/org.matrix.msc3723/versions", AuthScheme::None),
	(
		"POST",
		"/_matrix/federation/unstable/org.matrix.msc3843/rooms/{}/report/{}",
		AuthScheme::ServerSignatures,
	),
	(
		"GET",
		"/_matrix/federation/unstable/org.matrix.msc3916.v2/media/download/{}",
		AuthScheme::ServerSignatures,
	),
	(
		"GET",
		"/_matrix/federation/unstable/org.matrix.msc3916.v2/media/thumbnail/{}",
		AuthScheme::ServerSignatures,
	),
	(
		"GET",
		"/_matrix/federation/unstable/xyz.amorgan.knock/make_knock/{}/{}",
		AuthScheme::ServerSignatures,
	),
	(
		"PUT",
		"/_matrix/federation/unstable/xyz.amorgan.knock/send_knock/{}/{}",
		AuthScheme::ServerSignatures,
	),
	("PUT", "/_matrix/federation/v1/3pid/onbind", AuthScheme::None),
	("GET", "/_matrix/federation/v1/backfill/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/edutypes", AuthScheme::None),
	("GET", "/_matrix/federation/v1/event/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/event_auth/{}/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v1/exchange_third_party_invite/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/federation/v1/get_missing_events/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/hierarchy/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v1/invite/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/make_join/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/make_knock/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/make_leave/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/media/download/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/media/thumbnail/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/openid/userinfo", AuthScheme::None),
	("GET", "/_matrix/federation/v1/publicRooms", AuthScheme::ServerSignatures),
	("POST", "/_matrix/federation/v1/publicRooms", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/query/directory", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/query/profile", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/query/{}", AuthScheme::AccessToken),
	("PUT", "/_matrix/federation/v1/send/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v1/send_join/{}/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v1/send_knock/{}/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v1/send_leave/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/state/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/state_ids/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/timestamp_to_event/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/user/devices/{}", AuthScheme::ServerSignatures),
	("POST", "/_matrix/federation/v1/user/keys/claim", AuthScheme::ServerSignatures),
	("POST", "/_matrix/federation/v1/user/keys/query", AuthScheme::ServerSignatures),
	("GET", "/_matrix/federation/v1/version", AuthScheme::None),
	("PUT", "/_matrix/federation/v2/invite/{}/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v2/send_join/{}/{}", AuthScheme::ServerSignatures),
	("PUT", "/_matrix/federation/v2/send_leave/{}/{}", AuthScheme::ServerSignatures),
	("GET", "/_matrix/foo/org.bar.msc9000/baz", AuthScheme::AccessToken),
	("GET", "/_matrix/foo/org.bar.msc9000/qux", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2", AuthScheme::None),
	("POST", "/_matrix/identity/v2/3pid/bind", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2/3pid/getValidated3pid/", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/3pid/unbind", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/account", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/account/logout", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/account/register", AuthScheme::None),
	("GET", "/_matrix/identity/v2/hash_details", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/lookup", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2/pubkey/ephemeral/isvalid", AuthScheme::None),
	("GET", "/_matrix/identity/v2/pubkey/isvalid", AuthScheme::None),
	("GET", "/_matrix/identity/v2/pubkey/{}", AuthScheme::None),
	("POST", "/_matrix/identity/v2/sign-ed25519", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/store-invite", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2/terms", AuthScheme::None),
	("POST", "/_matrix/identity/v2/terms", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/validate/email/requestToken", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2/validate/email/submitToken", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/validate/email/submitToken", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/validate/msisdn/requestToken", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/v2/validate/msisdn/submitToken", AuthScheme::AccessToken),
	("POST", "/_matrix/identity/v2/validate/msisdn/submitToken", AuthScheme::AccessToken),
	("GET", "/_matrix/identity/versions", AuthScheme::None),
	("POST", "/_matrix/key/v2/query", AuthScheme::None),
	("GET", "/_matrix/key/v2/query/{}", AuthScheme::None),
	("GET", "/_matrix/key/v2/server", AuthScheme::None),
	("GET", "/_matrix/media/r0/config", AuthScheme::AccessToken),
	("GET", "/_matrix/media/r0/download/{}/{}", AuthScheme::None),
	("GET", "/_matrix/media/r0/download/{}/{}/{}", AuthScheme::None),
	("GET", "/_matrix/media/r0/preview_url", AuthScheme::AccessToken),
	("GET", "/_matrix/media/r0/qux", AuthScheme::AccessToken),
	("GET", "/_matrix/media/r0/thumbnail/{}/{}", AuthScheme::None),
	("POST", "/_matrix/media/r0/upload", AuthScheme::AccessToken),
	("POST", "/_matrix/media/unstable/fi.mau.msc2246/create", AuthScheme::AccessToken),
	("PUT", "/_matrix/media/unstable/fi.mau.msc2246/upload/{}/{}", AuthScheme::AccessToken),
	("POST", "/_matrix/media/v1/create", AuthScheme::AccessToken),
	("GET", "/_matrix/media/v3/config", AuthScheme::AccessToken),
	("GET", "/_matrix/media/v3/download/{}/{}", AuthScheme::None),
	("GET", "/_matrix/media/v3/download/{}/{}/{}", AuthScheme::None),
	("GET", "/_matrix/media/v3/preview_url", AuthScheme::AccessToken),
	("GET", "/_matrix/media/v3/qux", AuthScheme::AccessToken),
	("GET", "/_matrix/media/v3/thumbnail/{}/{}", AuthScheme::None),
	("POST", "/_matrix/media/v3/upload", AuthScheme::AccessToken),
	("PUT", "/_matrix/media/v3/upload/{}/{}", AuthScheme::AccessToken),
	(
		"POST",
		"/_matrix/policy/unstable/org.matrix.msc4284/event/{}/check",
		AuthScheme::ServerSignatures,
	),
	("POST", "/_matrix/policy/unstable/org.matrix.msc4284/sign", AuthScheme::ServerSignatures),
	("POST", "/_matrix/push/v1/notify", AuthScheme::None),
	("POST", "/_matrix/some/endpoint", AuthScheme::None),
	("POST", "/_matrix/some/endpoint/{}", AuthScheme::None),
	("GET", "/_matrix/static/client/login/", AuthScheme::None),
];
